### ISSUE TITLE
Example is not compatible with CMSIS-Toolbox 1.2.0

### ISSUE THREAD

**Issue by jkrech** [KeilChris/MultiBlinky#1]
The example in this repository is not compatible with CMSIS-Toolbox 1.2.0 as this new version requires that the configuration files for the layers are stored within the layer directory's RTE folder (by default).

Since the `RTE` directory in the layer directories are currently empty, `csolution` is copying default configuration files instead of the configured files located in the project's `RTE` directory

**Comment by KeilChris** [comment]
Example is now compatible with CMSIS-Toolbox 1.5.0.
